logger:
  # Optional log file, set to false or remove to disable it
  file: log/phobos.log
  # Optional output format for stdout, default is false (human readable).
  # Set to true to enable json output.
  stdout_json: false
  level: info
  # Comment the block to disable ruby-kafka logs
  ruby_kafka:
    level: error

kafka:
  # identifier for this application
  client_id: phobos-test
  # timeout setting for connecting to brokers
  connect_timeout:
  # timeout setting for socket connections
  socket_timeout:
  # PEM encoded CA cert to use with an SSL connection (string)
  ssl_ca_cert:
  # PEM encoded client cert to use with an SSL connection (string)
  # Must be used in combination with ssl_client_cert_key
  ssl_client_cert:
  # PEM encoded client cert key to use with an SSL connection (string)
  # Must be used in combination with ssl_client_cert
  ssl_client_cert_key:
  # list of brokers used to initialize the client ("port:protocol")
  seed_brokers:
    - localhost:9092

producer:
  # number of seconds a broker can wait for replicas to acknowledge
  # a write before responding with a timeout
  ack_timeout: 5
  # number of replicas that must acknowledge a write, or `:all`
  # if all in-sync replicas must acknowledge
  required_acks: :all
  # number of retries that should be attempted before giving up sending
  # messages to the cluster. Does not include the original attempt
  max_retries: 2
  # number of seconds to wait between retries
  retry_backoff: 1
  # number of messages allowed in the buffer before new writes will
  # raise {BufferOverflow} exceptions
  max_buffer_size: 1000
  # maximum size of the buffer in bytes. Attempting to produce messages
  # when the buffer reaches this size will result in {BufferOverflow} being raised
  max_buffer_bytesize: 10000000
  # name of the compression codec to use, or nil if no compression should be performed.
  # Valid codecs: `:snappy` and `:gzip`
  compression_codec:
  # number of messages that needs to be in a message set before it should be compressed.
  # Note that message sets are per-partition rather than per-topic or per-producer
  compression_threshold: 1
  # maximum number of messages allowed in the queue. Only used for async_producer
  max_queue_size: 1000
  # if greater than zero, the number of buffered messages that will automatically
  # trigger a delivery. Only used for async_producer
  delivery_threshold: 0
  # if greater than zero, the number of seconds between automatic message
  # deliveries. Only used for async_producer
  delivery_interval: 0
  # Set this to true to keep the producer connection between publish calls.
  # This can speed up subsequent messages by around 30%, but it does mean
  # that you need to manually call sync_producer_shutdown before exiting,
  # similar to async_producer_shutdown.
  persistent_connections: false
  # kafka here supports the same parameters as the top-level, allowing custom connection
  # configuration details for producers
  kafka:
    connect_timeout: 120

consumer:
  # number of seconds after which, if a client hasn't contacted the Kafka cluster,
  # it will be kicked out of the group
  session_timeout: 30
  # interval between offset commits, in seconds
  offset_commit_interval: 10
  # number of messages that can be processed before their offsets are committed.
  # If zero, offset commits are not triggered by message processing
  offset_commit_threshold: 0
  # the time period that committed offsets will be retained, in seconds. Defaults to the broker setting.
  offset_retention_time:
  # interval between heartbeats; must be less than the session window
  heartbeat_interval: 10
  # kafka here supports the same parameters as the top-level, allowing custom connection
  # configuration details for consumers
  kafka:
    connect_timeout: 130

backoff:
  min_ms: 1000
  max_ms: 60000

listeners:
  - handler: Reviews::Consumer
    topic: test.users
    group_id: reviews
  - handler: Reviews::Consumer
    topic: test.books
    group_id: reviews
